apiVersion: apps/v1
kind: Deployment
metadata:
  name: auth-deployment
  namespace: edugo-auth
spec:
  replicas: 2
  selector:
    matchLabels:
      app: auth
  template:
    metadata:
      labels:
        app: auth
    spec:
      containers:
        - name: auth
          image: australia-southeast2-docker.pkg.dev/sit707-25t1-tepaiyan-8729201/my-docker-repo/auth-service:latest
          imagePullPolicy: Always
          ports:
            - containerPort: 4000
          env:
            - name: MONGO_USER
              valueFrom:
                secretKeyRef:
                  name: auth-secret
                  key: MONGO_USER
            - name: MONGO_PASSWORD
              valueFrom:
                secretKeyRef:
                  name: auth-secret
                  key: MONGO_PASSWORD
            - name: JWT_SECRET
              valueFrom:
                secretKeyRef:
                  name: auth-secret
                  key: JWT_SECRET
          livenessProbe:
            httpGet:
              path: /health
              port: 4000
            initialDelaySeconds: 10
            periodSeconds: 20
          readinessProbe:
            httpGet:
              path: /ready
              port: 4000
            initialDelaySeconds: 5
            periodSeconds: 10
