apiVersion: apps/v1
kind: Deployment
metadata:
  name: mongo-standalone
  namespace: edugo-auth
spec:
  replicas: 1
  selector:
    matchLabels:
      app: mongo-standalone
  template:
    metadata:
      labels:
        app: mongo-standalone
    spec:
      containers:
        - name: mongo
          image: mongo:6.0
          resources:
            requests:
              cpu: "250m"
              memory: "512Mi"
            limits:
              cpu: "500m"
              memory: "1Gi"
          volumeMounts:
            - name: data
              mountPath: /data/db
          ports:
            - containerPort: 27017
          env:
            - name: MONGO_INITDB_DATABASE
              value: authdb
            - name: MONGO_INITDB_ROOT_USERNAME
              value: authuser
            - name: MONGO_INITDB_ROOT_PASSWORD
              value: authpass
      volumes:
        - name: data
          persistentVolumeClaim:
            claimName: mongo-pvc
---
apiVersion: v1
kind: Service
metadata:
  name: mongo-standalone
  namespace: edugo-auth
spec:
  selector:
    app: mongo-standalone
  ports:
    - port: 27017
      targetPort: 27017
      protocol: TCP
